name: Checks

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Verify
        run: make verify
